kind: Ingress
metadata:
  name: helloworld
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
      - helloworld.com
      secretName: tls-cert
  rules:
    - host: helloworld.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                - name: helloworld
                  port:
                   number: 80

#    - host: helloworld.com
      https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                - name: helloworld
                  port:
                   number: 443
