apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
  labels:
    app: appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: appname
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: appname
        image: ghcr.io/sudeeps91/imagename
        resources:
          requests:
             cpu: 500m
        ports:
        - containerPort: 80
