apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
  labels:
    app: appname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
      - name: appname
        image: ghcr.io/sudeeps91/imagename:latest
        resources:
          requests:
             cpu: 500m
        ports:
        - containerPort: 80
