apiVersion: v1
kind: Service
metadata:
  name: appname
  labels:
    app: appname
spec:
  type: ExternalName
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30251
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30252
  selector:
    app: appname
